env:
  NUKE_TELEMETRY_OPTOUT: 1
name: continuous
on:
  push:
    branches-ignore:
      - trash

jobs:
  continuous:
    name: Run
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout CEFSharpDockerfiles
        uses: actions/checkout@v3
        with:
          repository: mitchcapper/CefSharpDockerfiles
          path: CefSharpDockerfiles

      - name: build
        shell: pwsh
        continue-on-error: true
        run: ./main/hub_build.ps1 -Passthru
        
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 1440
        with:
          limit-access-to-actor: true