env:
  NUKE_TELEMETRY_OPTOUT: 1
name: continuous
on:
  push:
    branches-ignore:
      - trash

jobs:
  jvs-base-image-cache:
    name: vs-base-image-cache
    runs-on: windows-latest
    steps:
      - name: Cache VSBuild Lookup
        id: cache-vsbuild
        uses: actions/cache@v3
        with:
          path: c:/temp/cache
          key: docker_vs    
      - name: make vscache
        if: steps.cache-vsbuild.outputs.cache-hit != 'true'
        shell: powershell
        run: ./main/hub_build.ps1 -Verbose -Special MakeVSCache

  jcef-source-artifact:
    name: cef-source-artifact
    runs-on: windows-latest
    needs: jvs-base-image-cache
    steps:
      - name: existing artifact check
        id: existing-artifact-check
        uses: xSAVIKx/artifact-exists-action@v0
        with:
            name: 'cef_src'

      - name: Cache VSBuild Lookup
        id: cache-vsbuild
        if: steps.existing-artifact-check.outputs.exist != 'true'
        uses: actions/cache@v3
        with:
          path: c:/temp/cache
          key: docker_vs    

      - name: vscache restore
        if: steps.existing-artifact-check.outputs.exist != 'true'
        shell: powershell
        run: ./main/hub_build.ps1 -Verbose -Special RestoreVSCache
      
      - name: make cef source artifact
        if: steps.existing-artifact-check.outputs.exist != 'true'
        shell: powershell
        run: ./main/hub_build.ps1 -Verbose -Special MakeCefSrcArtifact

      - name: Upload CEF Source artifact
        uses: actions/upload-artifact@v3
        if: steps.existing-artifact-check.outputs.exist != 'true'
        with:
          name: cef_src
          path: c:/temp/artifacts


  jcef-compile:
    name: jcef-compile
    runs-on: windows-latest
    needs: [jvs-base-image-cache, jcef-source-artifact]
    steps:
      - name: Cache VSBuild Lookup
        id: cache-vsbuild
        uses: actions/cache@v3
        with:
          path: c:/temp/cache
          key: docker_vs

      - name: vscache restore
        shell: powershell
        run: ./main/hub_build.ps1 -Verbose -Special RestoreVSCache

      - name: Download previous CEF Source cache artifact
        uses: actions/download-artifact@v3
        with:
          name: cef_src
          required: true
          path: c:/temp/artifacts        


      - name: cef source restore
        shell: powershell
        run: ./main/hub_build.ps1 -Verbose -Special RestoreCefSrcArtifact

      - name: compile cef
        if: steps.cache-vsbuild.outputs.cache-hit != 'true'
        shell: powershell
        run: ./main/hub_build.ps1 -Verbose -Special CefBuild

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 1440
        with:
         limit-access-to-actor: true
      
